### ISSUE TITLE
Add Apify SDK for Python to the Python images

### ISSUE THREAD

**Issue by fnesveda** [apify/apify-actor-docker#89]
After the Python SDK is [published](https://github.com/apify/apify-sdk-python/issues/1), we need to have it preinstalled in the Python actor images instead of the API client.

We need:
- [x] base image with just Python SDK
- [x] base image with Python SDK and Selenium
- [x] base image with Python SDK and Playwright

**Comment by fnesveda** [comment]
This is done by #92, #93 and #94
